apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    myapp: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    command: ['sh', '-c', "echo $(MY_VAR)"]
env:
-  name: MY_VAR
   valurFrom:
     configMapKeyRef:
       name: ConfigMap
       key: myValue

