apiVersion: v1
kind: service
metadata:
  name: javaservice
spec:
  selectors:
    matchLabels:
      app: java2
  type: LoadBalancer
  ports:
    targetPort: 8080
    containerPort: 8080
    nodePort: 8080


