pipeline {
 agent any
  stages {
    stage('build') {
         steps {
             sh 'docker build -t frontend roboshop/frontend/'
                   }
                 }
            stage('push'){
              steps{
              sh 'aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/e7e5w0j6'
              sh 'docker tag frontend:latest public.ecr.aws/e7e5w0j6/chantiecr:latest'
              sh 'docker push public.ecr.aws/e7e5w0j6/chantiecr:latest'
           }
           }
           }

       }