apiVersion: v1
kind: Pod
metadata:
  name: app1
spec:
  containers:
  - name: app
    image: nginx:latest
    ports:
    - containerPort: 80

apiVersion: v1
# kind: Pod
# metadata:
#   name: webserver
# spec:
#   containers:
#   - name: webserver
#     image: nginx:latest
#     ports:
#     - containerPort: 80
#   - name: webwatcher
#     image: afakharany/watcher:latest
