apiVersion: v1
kind: Pod
metadata:
 name: mypod
 labels:
   app: myapp
 spec:
   containers:
   - name: myapp-container
     image: nginx
     command:   ['sh' , '-c' , 'echo hello chanti && sleep 3000']