apiVersion: v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 2
  containers:
    name: mongodb
    image: mongo
    ports:
    - containerPort: 27017
      type: LoadBalancer
      targetport: 27017
      port: 27017
    env:
    - name: MONGO_INITDB_ROOT_USERNAME
      value: admin
    - name: MONGO_INITDB_ROOT_PASSWORD
      value: admin