apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx1.7.9
  name: nginx1.7.9
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx1.7.9
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx1.7.9
    spec:
      containers:
      - image: nginx:1.7.9
        name: nginx
        resources: {}
status: {}
